### ISSUE TITLE
table cell style

### ISSUE THREAD

**Issue by OtharSmirnow** [jdum/odfdo#10]
hi,
I can't find the way to apply text and table style on a cell.

table cell style (created with create_table_cell_style) controls borders, padding, shadow and background (no text style)
paragraph style (created in style document) controls all I need except borders

is there a way to control both for table-cell?

I thought about applying table template, but it is not merged from style_document.

**Comment by jdum** [comment]
maybe see some sample is close to your need in odfdo-contrib (script generating a .ods from python lists)
