### ISSUE TITLE
Column table styling

### ISSUE THREAD

**Issue by bastien34** [jdum/odfdo#17]
Hi, after few tries, I'm wondering if it's possible to apply a column style (basically a column width) in a table appended in a text document. I've seen the recipe for doing a such styling in a spreadsheet, unfortunately, this doesn't work in my text document.

```
col_style` = Style("table-column", width="3.6cm", bold=True)
 name = doc.insert_style(style=col_style, automatic=True)
 for column in table.get_columns():
            column.style = name
            table.set_column(column.x, column)
```

Is there a way to set the width of a column in a text document, then?

**Comment by bastien34** [comment]
Thanks for your quick answer !

Unfortunately it doesn't work. It has no effect of the created table. So I formatted a table and I copied the serialized column styles. I only have 2 columns. The very strange result is that it adds a third column of equal  width.

I let here my attempt:
`
def col_A() -> Style:
    return Element.from_tag(
        '<style:style style:name="mission-table.A" style:family="table-column">'
        '<style:table-column-properties style:column-width="5.609cm" style:rel-column-width="3180*"/>'
        '</style:style>'
    )
`
And to apply style:

`
        col = table.get_column(0)
        col.style = 'mission-table.A'
        table.set_column(0, col)
`
I do the same for columns A and B and it adds a third empty column!

**Comment by jdum** [comment]
My snippet works here, so there is another pb elsewhere. In your last attempt dont forget to insert style in doc: 
```
style = col_A()
document.insert_style(style=style, automatic=True) 
```
And then it works

**Comment by bastien34** [comment]
I created a snippet that can be read easily. It's a minimalist creation of a table with the attempt of doing a table with defined sized columns. When I run it, I get a 3 columns table which is to me out of sense.

```
#!/usr/bin/env python

from odfdo import Table, Element
from odfdo import Document, Style


def col_A() -> Style:
    return Element.from_tag(
        '<style:style style:name="mission-table.A" style:family="table-column">'
        '<style:table-column-properties style:column-width="5.609cm" style:rel-column-width="3180*"/>'
        '</style:style>'
    )


def col_B() -> Style:
    return Element.from_tag(
        '<style:style style:name="mission-table.B" style:family="table-column">'
        '<style:table-column-properties style:column-width="11.389cm" style:rel-column-width="6457*"/>'
        '</style:style>'
    )


if __name__ == "__main__":

    document = Document("text")
    body = document.body

    data = [
        ('Mission', 'Nom de la mission'),
        ('Durée', 'mission length'),
        ('Info', 'descr'),
    ]

    col_a = document.insert_style(col_A())
    col_b = document.insert_style(col_B())

    table = Table('mission-table', width=2, height=3)
    table.set_values(data)
    document.body.append(table)

    col = table.get_column(0)
    col.style = col_a
    table.set_column(0, col)

    col = table.get_column(1)
    col.style = col_b
    table.set_column(1, col)

    document.save(target="/home/bastien/test_table.odt", pretty=True)

```

If you'd like to give it a try, you only need to change the path to save the doc.
