### ISSUE TITLE
The default language is french. It is no where documented how to change it.

### ISSUE THREAD

**Issue by pdenapo** [jdum/odfdo#23]
The default document language is french. This might be not what most users want. The code in the  meta.py example

document.set_language('fr-FR')

does not work.  This should be the most pythonic way of doing this.

**Comment by jdum** [comment]
Sorry, but you're wrong: The default document language is ... empty. But you are right the example is erroneous, the actual working code is meta.get_language(), with meta being: document.get_part("meta.xml")

You have a working example the the recipe "show_meta_data.py"

I'm sorry that the rather old code base of this software is too close to ODF, and so far from your dreams.

**Comment by jdum** [comment]
More about default templates: 

- To create a new document, odfdo uses a template (like LibreOffice or other implementations). To use your own template (with chosen styles, etc.), just do: `document=Document.new("my_template.ott")`
 
- Of course you can change also in the source code the file odfdo/templates/text.ott

**Comment by jdum** [comment]
It should be solved in new release: version 3.16.0

Just do: 
`document.language = 'en-US'`

And both default styles and metadata should be set, making LibreOffice happy.
