### ISSUE TITLE
Generating an spreadsheet, it has an extra empty sheet.

### ISSUE THREAD

**Issue by pdenapo** [jdum/odfdo#24]
I have created a test ods document using the following code:

````
from odfdo import Document, Table

body = doc.body
table = Table("Frequency Table")
table.set_values([[1,2],[2,3]])
body.append(table)

doc.save("hello.ods",pretty=True)

````

It has an empty extra empty sheet "Feuille 1" !

**Comment by jdum** [comment]
Yes, it has an empty sheet with default french name. Apparently you don't like French ? It is a feature that was requested years ago that a default empty .ods document was not absolutely empty, like expected by some libreoffice users. 

A safe way to start on an empty document is clear():

doc = Document("spreadsheet")  # missing line in your example
doc.body.clear()  # clear the body before append things.

(Other ways are possible)

If you struggle with odfdo for with numeric content in .ods files, you can try this tools based on odfdo: odsgenerator and odsparsator

**Comment by paulpall** [comment]
I don't have anything against French but it does seem a bit odd to me that I would have to clear a newly created object. Having worked with other spreadsheet libraries, like _openpyxl_, my thinking was to create: `document` -> `sheet` -> `row` -> `cell`. Then again, I suppose that could lead to broken documents, since _LibreOffice_ creates a default page as well. Perhaps the `Document()` constructor could be tweaked to include an option to create a truly clear spreadsheet in one line, while retaining the current solution as default?

**Comment by jdum** [comment]
Hello, frankly, I am also quite shocked to start with a document that is not really empty. I myself often get trapped when writing a test case. I should explore your proposal of a "clear=True" option.  About a "really clear document" concept:
 - The original project is quite old, and the implicit "not really empty" thing was not a good design choice, but I feel uncomfortable breaking too many things on compatibility.
 - If we had a "pure standard ODF only" implementation, a new document could be created without any default style (the "Standard" style), default fonts, and maybe the actual document type... Impossible to initialize such a document properly.
 - So the choice was to be closer to a GUI tool like Libreoffice: start with a template. Then all the problems, like the default language, and other default values. I believe the "marketing" choice was to be able to nicely display an empty document, so with an existing first table in the spreadsheet. Oops. And initial founding being French... (Note to myself for a future version: maybe try to detect local LANG and apply to the newly created document ?).
 - It should be possible to create a new Document from any specific template with `Document.new(template=whatever)`, which could partially solve the situation...
