### ISSUE TITLE
Referenced scripts from `test_scripts.sh` missing?

### ISSUE THREAD

**Issue by stefan6419846** [jdum/odfdo#31]
I just had a look at https://github.com/jdum/odfdo/blob/master/test/test_scripts.sh, which references some scripts which are missing in the repository, like `lpod-convert.py`: https://github.com/jdum/odfdo/tree/master/scripts They apparently only exist on the "original" repository: https://github.com/lpod/lpod-python/tree/master/scripts

Due to not using any CI (like GitHub Actions), it seems like this has not been obvious yet.

**Comment by jdum** [comment]
Hi,
Thanks, this test_scripts.sh is deprecated.  And GH actions could not see that. Just run test.sh or pytest from the test folder.
