### ISSUE TITLE
Spreadsheet document with style not correctly visualized in LibreOffice

### ISSUE THREAD

**Issue by SevC10** [jdum/odfdo#41]
I try to create a new spreadsheet document with some formatting applied to the text (bold text).
If I open the generated ods file with Excel, it correctly shows the bold text, while if I open the ods file with LibreOffice, the bold formatting is not present.
I know there are issue with styles, but I wonder if a simple case could be fixed.

Thank you!
Severino

_System information:_

- Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
- odfdo==3.7.7
- Microsoft® Excel® per Microsoft 365 MSO (Versione 2404 Build 16.0.17531.20140) a 64 bit 
- LibreOffce: Version: 7.5.9.2 (X86_64) / LibreOffice Community
Build ID: cdeefe45c17511d326101eed8008ac4092f278a9
CPU threads: 8; OS: Windows 10.0 Build 19045; UI render: Skia/Raster; VCL: win
Locale: it-IT (it_IT); UI: it-IT
Calc: threaded

_Minimal working example:_

    from odfdo import Document, Table, Style

    STILE_GRASS = 'grassetto'

    def crea_stile_grassetto(document):
        
        nome_stile = STILE_GRASS
        
        style = Style(
            family='text',
            name=nome_stile,
            display_name=nome_stile,
            bold=True,
        )
        
        document.insert_style(style)

    def test_bold_style():
        
        doc = Document('spreadsheet')
        
        body = doc.body
        body.clear()
        
        crea_stile_grassetto(doc)
        
        
        nome_foglio = 'test'
        foglio = Table(nome_foglio)
        
        foglio.set_value((0, 0), 'BOLD', style=STILE_GRASS)
        foglio.set_value((0, 1), 'NO BOLD')
        
        body.append(foglio)
        
        
        file_out = 'test_style.ods'
        doc.save(file_out)
        
        print(f'saved: {file_out}')

    if __name__ == '__main__':
        test_bold_style()

**Comment by jdum** [comment]
Hi, just change the Style object as:

```
style = Style(
        family="table-cell",
        area="text",
        name=nome_stile,
        display_name=nome_stile,
        bold=True,
    )
```

**Comment by SevC10** [comment]
It works!
Thank you very much for your support!
Severino

**Comment by jdum** [comment]
:-)
Programmatically generating styles is hell.
