### ISSUE TITLE
Method para.append_plain_text() trims whitespaces before text

### ISSUE THREAD

**Issue by mlwesoly** [jdum/odfdo#48]
Hello,

i use
```
para = Paragraph("", style="Standard Linux") 
para.append_plain_text() 
```
for adding text like:
```
 1 some information  (one whitespace before the number)
 2 some more information  (one whitespace before the number)
 ...
10 in the middle of the block
```
Now the issue that i have with the result is, that the whitespaces before the rest of the text get trimmed.
In previous versions of odfdo i added a workaround  in paragraph_base.py. Now with the rewrite of it i wanted to ask before putting effort.
Is there an easy way, so the whitespace from the beginning of the line does not get trimmed? And is this behavior as it should be?
Thank you in advance for your help and time!

EDIT: Just found the _plain_text_splitted method, where i can add my workaround. Still I'm interested to know more about this behavior.

**Comment by jdum** [comment]
Hi, this is a beautiful bug ;-)
What I see:
- append°plain_text() does not trim the leading spaces (I can see them in the .xml file)
- however LibreOffice does remove the first space
- what the standard is saying seems quite strange:

**Comment by mlwesoly** [comment]
Thank you very much for the comprehensive answer. I will also read a bit more into this, because what i read from your quotes makes me wonder, why did a committee decide that leading space characters should be removed. Trailing ones I can understand. Anyway that is for another day, i thank you for having a look into this topic. 

my current workaround looks like this, also splitting the one space at beginning and then adding a Spacer in form of the block length. ....let's just say, its working for me at the moment. But i know it is just a not beautiful solution.
```
_re_splitter = re.compile(r"(\n|\t|^ |  +)")
_re_space = re.compile(r"^  +$")
_re_space2 = re.compile(r"^ +$")

... lower in _plain_text_splitted

    continue
            if _re_space2.match(bloc):
                # follow ODF standard : n spaces => one space + spacer(n-1)
                # self.append(" ")
                elements.append(Spacer(len(bloc)))
                continue
            if _re_space.match(bloc):

```

**Comment by jdum** [comment]
The new version 3.9 should fix the bug

**Comment by mlwesoly** [comment]
I tried it and until now it works perfectly. Thank you very much!
