### ISSUE TITLE
How to replace a text with a respect to spaces and new lines

### ISSUE THREAD

**Issue by den1251** [jdum/odfdo#52]
```
body.replace("MAIN_TEXT", """
some
multiline \n\n         text
""")
```
this just replaces the text with `some multiline text`. How to replace the text including spaces greater than 1 and new lines, so it will be:

```
some
multiline 
        text
```

**Comment by jdum** [comment]
Very interesting issue, thanks. (Thinking while writing response, no certainty in following lines)

Short answer: no easy way, very difficult. Maybe in a few weeks I cant propose something useable, not sure. (Depending of actual situation, cutting part or whole paragraph and recreate would be the easiest way?)

Longer answer: 

a) `body.replace()` aims to replace text by text.  And is tricky, it actually replaces all instances of the target pattern (it is a regex). See current docstring: 

```
Replace the pattern with the given text, or delete if text is an
empty string, and return the number of replacements. By default, only
return the number of occurences that would be replaced.

It cannot replace patterns found across several element, like a word
split into two consecutive spans.

Python regular expression syntax applies.
````

The missing part in this docstring: ***and can not create new XML elements.***

b) current: to achieve your goal, currently need to create the new paragraph element, cut the text pattern (or use `.replace()` for the end of the paragraph), and use `Element.insert()` or `Element.append()` to finish the job by adding the part after the "\n\n". Expensive solution.

b) semantic: 

- what you get: spaces and "\n" are ignored by ODF, by law, (and for many tech reasons).
- what you probably expect is replacing (in a text paragraph) some string and obtain (semantic) 2 separated paragraphs (the "\n\n" meaning). Which is not so easy. And, of course, if the pattern string is located in a <span>, it becomes hell (cutting the spans, create 2 paragraphs, reimplement a second span, ...).  And paragraph or span are not the only ODF element that contain text. Note that `.replace()` can be called on any element, and ODF standard should apply (ie. you cant create a paragraph inside a span...)

c) history: origins of this library is a mapping of actual ODF underlying structure. With very little syntactic sugar.  I did open the Pandora's box by allowing translating by default "\n" and spaces in a paragraph string to some ODF <linebreak> and such. 

c) hope 1: maybe I cant use some tricks on several elements (like paragraphs and headers) to translate spaces and \n into something useful. However that would induce different behaviors depending of the class of the element (spans? footnotes?). That could also break compatibility with previous versions (then requiring new method name). 

d) hope 2: allow replacing by anything. I mean not only text by text, but text by any XML tree. Of course, you dont want to use this directly. But that is what needs to be done internally.

**Comment by den1251** [comment]
My solution was just to add paragraphs/headers etc. instead of replacing

**Comment by jdum** [comment]
The version 3.13.5 added the option `formatted` to script `odfdo-replace` and method `.replace()` to interpret the space, tab and CR of the replacement string. This seems to meet your need.
